import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Arush Bodla",
  description: "Generated by create next app",
  icons: {
    icon: "/ArushBodlaWithoutBackground.svg",
  },
  openGraph: {
    title: "Arush Bodla",
    description: "My works",
    url: "https://arushbodla.vercel.app",
    type: "website",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add Google site verification meta tag */}
        <meta name="google-site-verification" content="xQooeeOGkIFsaXmuJkqJBUlJmm1vAjHmQ3KWt84_5zA" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
